//! Generate `AnkiRPC.swift` from anki's protobuf descriptor set.
//!
//! rslib dispatches RPCs by integer `(service, method)` indices that its
//! build script derives from the descriptor pool (`anki_proto_gen::get_services`).
//! We reuse exactly that function so the Swift constants can never drift from
//! the Rust dispatch table.
//!
//! Usage: dispatch-gen <anki_descriptors.bin> <anki-git-sha>

use std::env;
use std::fs;

use anki_proto_gen::get_services;
use prost_reflect::DescriptorPool;

fn lower_camel(snake: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn main() {
    let mut args = env::args().skip(1);
    let descriptors = args.next().expect("usage: dispatch-gen <descriptors.bin> <anki-sha>");
    let anki_sha = args.next().unwrap_or_else(|| "unknown".into());
    let bytes = fs::read(&descriptors).expect("read descriptors");
    let pool = DescriptorPool::decode(bytes.as_slice()).expect("decode descriptor pool");
    let (_col_services, backend_services) = get_services(&pool);

    let mut out = String::new();
    out.push_str("// Generated by tools/dispatch-gen — DO NOT EDIT.\n");
    out.push_str(&format!("// anki commit: {anki_sha}\n"));
    out.push_str("// Service/method indices match rslib's generated run_service_method().\n\n");
    out.push_str("import Foundation\n\n");
    out.push_str("enum AnkiRPC {\n");
    for service in &backend_services {
        let short = service
            .name
            .trim_start_matches("Backend")
            .trim_end_matches("Service");
        if short == "Frontend" {
            continue; // not part of rslib's dispatch table
        }
        out.push_str(&format!("    enum {short} {{\n"));
        out.push_str(&format!(
            "        static let service: UInt32 = {}\n",
            service.index
        ));
        let mut methods: Vec<_> = service.all_methods().collect();
        methods.sort_by_key(|m| m.index);
        for m in methods {
            out.push_str(&format!(
                "        static let `{}`: UInt32 = {}\n",
                lower_camel(&m.name),
                m.index
            ));
        }
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    print!("{out}");
}
